// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'simple.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `configure_board`

class RustAlazarSettings {
  final int laserRepRateMHz;
  final int numBuffers;
  final int preTriggerSamples;
  final int postTriggerSamples;
  final int samplesPerRecord;
  final int bytesPerBuffer;
  final int recordsPerAcquisition;
  final int recordsPerBuffer;
  final bool live;
  final bool rampBoxAttached;
  final RustTriggerType trigger;
  final int triggerLevel;
  final double triggerDelaySec;
  final double triggerTimeoutSec;
  final int sampleRate;
  final int decimantionFactor;
  final List<List<RustChannel>> channels;
  final int admaFlags;

  const RustAlazarSettings({
    required this.laserRepRateMHz,
    required this.numBuffers,
    required this.preTriggerSamples,
    required this.postTriggerSamples,
    required this.samplesPerRecord,
    required this.bytesPerBuffer,
    required this.recordsPerAcquisition,
    required this.recordsPerBuffer,
    required this.live,
    required this.rampBoxAttached,
    required this.trigger,
    required this.triggerLevel,
    required this.triggerDelaySec,
    required this.triggerTimeoutSec,
    required this.sampleRate,
    required this.decimantionFactor,
    required this.channels,
    required this.admaFlags,
  });

  @override
  int get hashCode =>
      laserRepRateMHz.hashCode ^
      numBuffers.hashCode ^
      preTriggerSamples.hashCode ^
      postTriggerSamples.hashCode ^
      samplesPerRecord.hashCode ^
      bytesPerBuffer.hashCode ^
      recordsPerAcquisition.hashCode ^
      recordsPerBuffer.hashCode ^
      live.hashCode ^
      rampBoxAttached.hashCode ^
      trigger.hashCode ^
      triggerLevel.hashCode ^
      triggerDelaySec.hashCode ^
      triggerTimeoutSec.hashCode ^
      sampleRate.hashCode ^
      decimantionFactor.hashCode ^
      channels.hashCode ^
      admaFlags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustAlazarSettings &&
          runtimeType == other.runtimeType &&
          laserRepRateMHz == other.laserRepRateMHz &&
          numBuffers == other.numBuffers &&
          preTriggerSamples == other.preTriggerSamples &&
          postTriggerSamples == other.postTriggerSamples &&
          samplesPerRecord == other.samplesPerRecord &&
          bytesPerBuffer == other.bytesPerBuffer &&
          recordsPerAcquisition == other.recordsPerAcquisition &&
          recordsPerBuffer == other.recordsPerBuffer &&
          live == other.live &&
          rampBoxAttached == other.rampBoxAttached &&
          trigger == other.trigger &&
          triggerLevel == other.triggerLevel &&
          triggerDelaySec == other.triggerDelaySec &&
          triggerTimeoutSec == other.triggerTimeoutSec &&
          sampleRate == other.sampleRate &&
          decimantionFactor == other.decimantionFactor &&
          channels == other.channels &&
          admaFlags == other.admaFlags;
}

enum RustTriggerType {
  pll,
  ext,
  ;
}
