// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `calc_checksum`, `verify_checksum`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `control_ramp_box`

class RustRampBox {
  final String comPort;
  final int enableMode;
  final int enablePolarity;
  final int fastDacMode;
  final int fastDacSteps;
  final int fastDacPhase;
  final int fastDacScans;
  final int slowDacMode;
  final int slowDacSteps;
  final int slowDacScans;
  final RustRampBoxType boxType;

  const RustRampBox({
    required this.comPort,
    required this.enableMode,
    required this.enablePolarity,
    required this.fastDacMode,
    required this.fastDacSteps,
    required this.fastDacPhase,
    required this.fastDacScans,
    required this.slowDacMode,
    required this.slowDacSteps,
    required this.slowDacScans,
    required this.boxType,
  });

  @override
  int get hashCode =>
      comPort.hashCode ^
      enableMode.hashCode ^
      enablePolarity.hashCode ^
      fastDacMode.hashCode ^
      fastDacSteps.hashCode ^
      fastDacPhase.hashCode ^
      fastDacScans.hashCode ^
      slowDacMode.hashCode ^
      slowDacSteps.hashCode ^
      slowDacScans.hashCode ^
      boxType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustRampBox &&
          runtimeType == other.runtimeType &&
          comPort == other.comPort &&
          enableMode == other.enableMode &&
          enablePolarity == other.enablePolarity &&
          fastDacMode == other.fastDacMode &&
          fastDacSteps == other.fastDacSteps &&
          fastDacPhase == other.fastDacPhase &&
          fastDacScans == other.fastDacScans &&
          slowDacMode == other.slowDacMode &&
          slowDacSteps == other.slowDacSteps &&
          slowDacScans == other.slowDacScans &&
          boxType == other.boxType;
}

enum RustRampBoxType {
  v1,
  v2,
  ;
}
