// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `RustAlazarResponse`

Future<int> createAlazarStream() =>
    RustLib.instance.api.crateApiSimpleCreateAlazarStream();

Future<List<RustBoard>> detectBoardsRust() =>
    RustLib.instance.api.crateApiSimpleDetectBoardsRust();

class RustBoard {
  final int index;
  final RustCardType cardType;
  final List<RustChannel> channels;

  const RustBoard({
    required this.index,
    required this.cardType,
    required this.channels,
  });

  @override
  int get hashCode => index.hashCode ^ cardType.hashCode ^ channels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustBoard &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          cardType == other.cardType &&
          channels == other.channels;
}

enum RustCardType {
  c9350,
  c9440,
  c9462,
  ;
}

class RustChannel {
  final int index;

  const RustChannel({
    required this.index,
  });

  @override
  int get hashCode => index.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustChannel &&
          runtimeType == other.runtimeType &&
          index == other.index;
}
