// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<RustBoard> dco_decode_list_rust_board(dynamic raw);

  @protected
  List<RustChannel> dco_decode_list_rust_channel(dynamic raw);

  @protected
  RustBoard dco_decode_rust_board(dynamic raw);

  @protected
  RustCardType dco_decode_rust_card_type(dynamic raw);

  @protected
  RustChannel dco_decode_rust_channel(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<RustBoard> sse_decode_list_rust_board(SseDeserializer deserializer);

  @protected
  List<RustChannel> sse_decode_list_rust_channel(SseDeserializer deserializer);

  @protected
  RustBoard sse_decode_rust_board(SseDeserializer deserializer);

  @protected
  RustCardType sse_decode_rust_card_type(SseDeserializer deserializer);

  @protected
  RustChannel sse_decode_rust_channel(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_rust_board(
      List<RustBoard> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rust_channel(
      List<RustChannel> self, SseSerializer serializer);

  @protected
  void sse_encode_rust_board(RustBoard self, SseSerializer serializer);

  @protected
  void sse_encode_rust_card_type(RustCardType self, SseSerializer serializer);

  @protected
  void sse_encode_rust_channel(RustChannel self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
